PUT http://localhost:3000/api/boards/
Content-Type: application/json

{
    "boardId": 3,
    "content": "Comprar pan"
}

###
PUT  https://safe-forest-85043.herokuapp.com/api/boards/
Content-Type: application/json

{
    "boardId": 3,
    "content": "Comprar pan"
}

###
GET http://localhost:3000/api/boards/